# Generated by Django 6.0.3 on 2026-03-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tile',
            new_name='title',
        ),
    ]
